{% set name = "xeus-octave" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-octave/archive/v{{ version }}.tar.gz
  sha256: c0a5ddf85280bfcdce1bb3e77403f4546071f9f8aaa4c58a3f70df045c0e60e9

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - octave >=10.0,<11.0
    - xorg-libxfixes  # [linux]
    - glfw
    - glad
    - libpng
    - xeus >=5
    - xeus-zmq >=3.0,<4.0
    - nlohmann_json >=3.11.3,<4.0
  run:
    # Octave is missing a run_exports section
    - {{ pin_compatible('octave', max_pin='x.x') }}
    # Mesalib is missing a run_exports section
    - {{ pin_compatible('mesalib', max_pin='x.x') }}

test:
  requires:
    - jupyter_kernel_test >=0.4.3
    - nbval
    - pytest
    - pytest-rerunfailures
    # - {{ cdt('xorg-x11-server-xvfb') }}     # [linux]
  source_files:
    - test
  commands:
    - test -f ${PREFIX}/bin/xoctave  # [unix]
    - xoctave --version
    - pytest test -k 'not plot'
    - pytest test -k 'plot_plotly'
    # - xvfb-run pytest test -k 'plot_notebook'  # [linux]

about:
  home: https://github.com/rapgenic/xeus-octave
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Xeus kernel for Octave
  description: |
    Xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools Octave.

extra:
  recipe-maintainers:
    - IsabelParedes
    - rapgenic
    - SylvainCorlay
    - AntoinePrv
