context:
  name: xeus-octave
  version: 0.6.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-octave/archive/v${{ version }}.tar.gz
  sha256: d5a50c81992caeac0826b4028ce0c3c1792182ad82a4f9056cfe4a73cfb2fd54

build:
  number: 1
  skip:
  - win

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - pkg-config
    - cmake
    - make
  host:
    - octave >=10.0,<11.0
    - glfw
    - glad
    - libpng
    - xeus >=5
    - xeus-zmq >=3.0,<4.0
    - nlohmann_json
    - nlohmann_json-abi

tests:
- package_contents:
    files:
    - bin/xoctave
- script:
    - xoctave --version
    - pytest test -k 'not plot'
    - pytest test -k 'plot_plotly'
  requirements:
    run:
    - jupyter_kernel_test >=0.4.3
    - nbval
    - pytest
    - pytest-rerunfailures
  files:
    source:
    - test

about:
  homepage: https://github.com/rapgenic/xeus-octave
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Xeus kernel for Octave
  description: |
    Xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools Octave.

extra:
  recipe-maintainers:
    - JohanMabille
    - IsabelParedes
    - rapgenic
    - SylvainCorlay
    - AntoinePrv
